var myObject= {"codepen2023":[
  {"Pen":"Status indicators in CSS",
  "URL":"https://codepen.io/luisangelmaciel/pen/NWERjjv",
  "Creado":"21 Junio 2023"},
  {"Pen":"LocalStorage Checkbox - rememberme. jQuery",
  "URL":"https://codepen.io/luisangelmaciel/pen/yLQayqo",
  "Creado":"20 Junio 2023"},
  {"Pen":"Meta Comun ",
  "URL":"https://codepen.io/luisangelmaciel/pen/poQzZZB",
  "Creado":"5 junio 2023"},
  {"Pen":"Meta Webapp",
  "URL":"https://codepen.io/luisangelmaciel/pen/WNYeKKY",
  "Creado":"5 junio 2023"},
  {"Pen":"Button onclick=window.open & button onclick=location.href",
  "URL":"https://codepen.io/luisangelmaciel/pen/rNqaVNX",
  "Creado":"7 Abril 2023"},
  {"Pen":"Pre style Code ",
  "URL":"https://codepen.io/luisangelmaciel/pen/oNPoqxy",
  "Creado":" 9 Marzo 2023"},
   {"Pen":"Auto-format Date Input ",
  "URL":"https://codepen.io/luisangelmaciel/pen/ExOBLWB ",
  "Creado":"11 agosto 2023"},
  {"Pen":"Auto-format Date Input v2",
  "URL":"https://codepen.io/luisangelmaciel/pen/YzRJbEZ",
  "Creado":"11 agosto 2023"}
]};
