  var myObject= {
  "myApps":[
    {"img":"https://luisangelmaciel.github.io/yicel/yicel.svg",
    "URL":"",
    "alt":"Ladybug",
    "description":"El juego de Yisel"},   
	  {"img":"",
    "URL":"",
    "alt":"TotalLink",
	"description":"Involucre a su público objetivo con enlaces cortos personalizados  en la biografía que captan su atención"},     
    {"img":"",
    "URL":"https://luisangelmaciel.github.io/toxel.css/toxel.css",
    "alt":"Toxel",
	"description":"Involucre a su público objetivo con enlaces cortos personalizados  en la biografía que captan su atención"}, 
    {"img":"",
    "URL":"file:///C:/xbrpw.github.io/short-url/go/api/textAngular-1.5.16/demo/textAngular.com.html",
    "alt":"EditorAngular",
	"description":""}, 
    {"img":"https://www.xbr.pw/calculadora/favicon.svg",
     "URL":"https://www.xbr.pw/calculadora/",
     "alt":"Calculeitor",
	   "description":"Super calculeitor. Con registro de memoria. Para que no se te pase la operaión. Save Calculator", 
     "lighthouse":"100 100 100 100",
     "lighthouse-url":"https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fwww.xbr.pw%2Fcalculadora%2F&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa&utm_source=lh-chrome-ext"},
    {"img":"https://luisangelmaciel.github.io/Igglybuff/favicon.svg",
    "URL":"https://luisangelmaciel.github.io/Igglybuff/",
    "alt":"Igglybuff",
	"description":""},
    {"img":"",
    "URL":"",
    "alt":"",
	"description":""},
    {"img":"",
    "URL":"https://luisangelmaciel.github.io/css/style.css",
    "alt":"my stylamp",
    "description":""},
    {"img":"",
    "URL":"",
    "alt":"",
    "description":""},
     {"img":"",
    "URL":"",
    "alt":"",
    "description":""},
     {"img":"",
    "URL":"",
    "alt":"",
    "description":""},
     {"img":"",
    "URL":"",
    "alt":"",
    "description":""}
  ],
  "mySocialLinks":[ 
    {"img":"https://cutt.ly/img/icon.png",
    "URL":"https://cutt.ly/bio/VekyO",
    "alt":"Cutt.ly"},
    {"img":"https://glitch.com/favicon.ico",
    "URL":"https://lamparaps.glitch.me/",
    "alt":"glitch.me"},
    {"img":"",
    "URL":"",
    "alt":""},
    {"img":"",
    "URL":"",
    "alt":""},
    {"img":"https://image.typedream.com/cdn-cgi/image/width=80,height=80,quality=100,fit=crop/https://api.typedream.com/v0/document/public/b240dbd8-4dd7-4457-9772-b7c024a37932/2GR24wrIYYchz2ZO4RKiWjrepBA_logo.png?bucket=document",
    "URL":"https://dumpl.ink/aianapp/ulr-links-apps",
    "alt":"dumpl.ink"},    
    {"img":"https://sleek.bio/apple-touch-icon.png",
    "URL":"https://sleek.bio/Gameapps",
    "alt":"sleek.bio"}
  ],
  "myBlogs":[ 
    {"img":"https://glitch.com/favicon.ico",
    "URL":"https://bitacora-how-to-snippes.glitch.me/",
    "alt":"bitacora-how-to-snippes en glitch.me"},    
    {"img":"",
    "URL":"https://contratar-la-creacion-de-pagina-web.netlify.app/",
    "alt":""},      
    {"img":"",
    "URL":"",
    "alt":""},          
    {"img":"https://image.typedream.com/cdn-cgi/image/width=80,height=80,quality=100,fit=crop/https://api.typedream.com/v0/document/public/b240dbd8-4dd7-4457-9772-b7c024a37932/2GR24wrIYYchz2ZO4RKiWjrepBA_logo.png?bucket=document",
    "URL":"https://aianapp.typedream.app/",
    "alt":"aianapp en typedream.app"}
  ]
  };
