var myObject = {
    "proyectos-propios": [{
        "proyecto": "<b>Xiiber Travel</b> Viajes y experiencias para hombres gay ",
        "pageid": "https://luisangelmaciel.github.io/xiiber/",
    }, {
        "proyecto": "<b>Dragvesti</b> La carrera Drag Queen Online y En Vivo",
        "pageid": "https://luisangelmaciel.github.io/dragvesti/",
    }, {
        "proyecto": "<b>How to One</b> Code snippets para HTML, CSS & JavaScript",
        "pageid": "",
    }],
    "proyectos": [{
        "proyecto": "<b>Geus Gourmé</b> Productos gourmet artesanales",
        "pageid": "",
    }, {
        "proyecto": "<b>SiOkey</b> Verificadora de sitios",
        "pageid": "/siokey/index.html",
    }, {
        "proyecto": "<b>Tamales</b> Tamales de Bubulubu, Cremino, Ferrero, entre otros",
        "pageid": "/tamales/",
    }, {
        "proyecto": "<b>Mom´s Pizza</b> Pizzas con extra queso. Especialidad chorihawaian",
        "pageid": "",
    }, {
        "proyecto": "<b>Depravex</b> Sexshop online para hombres gay",
        "pageid": "/depravex/",
    }, {
        "proyecto": "<b></b>",
        "pageid": "/",
    }],
    "one": [{
        "title": "Code snippets para HTML, CSS & JavaScript",
        "pageid": "/templetes/catalogo.html",
    }],
    "Xiiber-travel": [{
        "title": "<b>Tepozspa</b> Spa exclusivo para hombres",
        "pageid": "",
    }],
    "app": [{
        "title": "<b>Frases de Goku</b> Épico random con las frases de Goku de Dragon Ball",
        "pageid": "",
    }],
    "notas": [{
        "proyecto": "Imagen recomendada 749 x 368 px",
    }, {
        "proyecto": "Style Guide. <) eBook | Martech para los nuevos. Explicado con bolitas y palitos ",
    }, {
        "proyecto": "",
    }],
    "hiHelloMaciel": [{
            "img-src": "ico.png",
            "fecha-De-Publicacion": "16 julio 2021",
            "a-href": "",
            "a-href-tittle": "Pokemon",
            "how-to-tittle": "",
            "el-Post": "♫ I wanna be the very best, like no one ever was ♫  ",
            "accion": "",
            "postFoto1": "",
            "altPostFoto1": "",
            "postFoto2": " ",
            "altPostFoto2": "",
            "postFoto3": "",
            "altPostFoto3": "",
            "postFoto4": "",
            "altPostFoto4": "",
            "score-lighthouse": "",
            "img-score-lighthouse": "",
        }, {
            "img-src": "ico.png",
            "fecha-De-Publicacion": "15 julio 2021",
            "a-href": "https://hihello.monster/how-to/Fold-out-menu-with-css-only",
            "a-href-tittle": "Fold out menu with css only  ",
            "how-to-tittle": "Fold out menu with css only",
            "el-Post": "Fold out menu with css only ",
            "accion": "Toch me",
            "postFoto1": "",
            "altPostFoto1": "",
            "postFoto2": " ",
            "altPostFoto2": "",
            "postFoto3": "",
            "altPostFoto3": "",
            "postFoto4": "",
            "altPostFoto4": "",
            "score-lighthouse": "",
            "img-score-lighthouse": "",
        }, {
            "img-src": "ico.png",
            "fecha-De-Publicacion": "16 julio 2021",
            "a-href": "",
            "a-href-tittle": "Pokemon",
            "how-to-tittle": "",
            "el-Post": "♫ I wanna be the very best, like no one ever was ♫  ",
            "accion": "",
            "postFoto1": "",
            "altPostFoto1": "",
            "postFoto2": " ",
            "altPostFoto2": "",
            "postFoto3": "",
            "altPostFoto3": "",
            "postFoto4": "",
            "altPostFoto4": "",
            "score-lighthouse": "",
            "img-score-lighthouse": "",
        }, {
            "img-src": "ico.png",
            "fecha-De-Publicacion": "16 julio 2021",
            "a-href": "",
            "a-href-tittle": "Pokemon",
            "how-to-tittle": "",
            "el-Post": "♫ I wanna be the very best, like no one ever was ♫  ",
            "accion": "",
            "postFoto1": "",
            "altPostFoto1": "",
            "postFoto2": " ",
            "altPostFoto2": "",
            "postFoto3": "",
            "altPostFoto3": "",
            "postFoto4": "",
            "altPostFoto4": "",
            "score-lighthouse": "",
            "img-score-lighthouse": "",
        }, {
            "img-src": "ico.png",
            "fecha-De-Publicacion": "16 julio 2021",
            "a-href": "",
            "a-href-tittle": "Pokemon",
            "how-to-tittle": "",
            "el-Post": "♫ I wanna be the very best, like no one ever was ♫  ",
            "accion": "",
            "postFoto1": "",
            "altPostFoto1": "",
            "postFoto2": " ",
            "altPostFoto2": "",
            "postFoto3": "",
            "altPostFoto3": "",
            "postFoto4": "",
            "altPostFoto4": "",
            "score-lighthouse": "",
            "img-score-lighthouse": "",
        }, {
            "img-src": "ico.png",
            "fecha-De-Publicacion": "16 julio 2021",
            "a-href": "",
            "a-href-tittle": "Pokemon",
            "how-to-tittle": "",
            "el-Post": "♫ I wanna be the very best, like no one ever was ♫  ",
            "accion": "",
            "postFoto1": "",
            "altPostFoto1": "",
            "postFoto2": " ",
            "altPostFoto2": "",
            "postFoto3": "",
            "altPostFoto3": "",
            "postFoto4": "",
            "altPostFoto4": "",
            "score-lighthouse": "",
            "img-score-lighthouse": "",
        },
        {
            "img-src": "ico.png",
            "fecha-De-Publicacion": "16 julio 2021",
            "a-href": "",
            "a-href-tittle": "Pokemon",
            "how-to-tittle": "",
            "el-Post": "♫ I wanna be the very best, like no one ever was ♫  ",
            "accion": "",
            "postFoto1": "",
            "altPostFoto1": "",
            "postFoto2": " ",
            "altPostFoto2": "",
            "postFoto3": "",
            "altPostFoto3": "",
            "postFoto4": "",
            "altPostFoto4": "",
            "score-lighthouse": "",
            "img-score-lighthouse": "",
        },
        {
            "img-src": "ico.png",
            "fecha-De-Publicacion": "16 julio 2021",
            "a-href": "",
            "a-href-tittle": "Pokemon",
            "how-to-tittle": "",
            "el-Post": "♫ I wanna be the very best, like no one ever was ♫  ",
            "accion": "",
            "postFoto1": "",
            "altPostFoto1": "",
            "postFoto2": " ",
            "altPostFoto2": "",
            "postFoto3": "",
            "altPostFoto3": "",
            "postFoto4": "",
            "altPostFoto4": "",
            "score-lighthouse": "",
            "img-score-lighthouse": "",
        },
        {
            "img-src": "ico.png",
            "fecha-De-Publicacion": "16 julio 2021",
            "a-href": "",
            "a-href-tittle": "Pokemon",
            "how-to-tittle": "",
            "el-Post": "♫ I wanna be the very best, like no one ever was ♫  ",
            "accion": "",
            "postFoto1": "",
            "altPostFoto1": "",
            "postFoto2": " ",
            "altPostFoto2": "",
            "postFoto3": "",
            "altPostFoto3": "",
            "postFoto4": "",
            "altPostFoto4": "",
            "score-lighthouse": "",
            "img-score-lighthouse": "",
        },
        {
            "img-src": "ico.png",
            "fecha-De-Publicacion": "16 julio 2021",
            "a-href": "",
            "a-href-tittle": "Pokemon",
            "how-to-tittle": "",
            "el-Post": "♫ I wanna be the very best, like no one ever was ♫  ",
            "accion": "",
            "postFoto1": "",
            "altPostFoto1": "",
            "postFoto2": " ",
            "altPostFoto2": "",
            "postFoto3": "",
            "altPostFoto3": "",
            "postFoto4": "",
            "altPostFoto4": "",
            "score-lighthouse": "",
            "img-score-lighthouse": "",
        },
        {
            "img-src": "ico.png",
            "fecha-De-Publicacion": "16 julio 2021",
            "a-href": "",
            "a-href-tittle": "Pokemon",
            "how-to-tittle": "",
            "el-Post": "♫ I wanna be the very best, like no one ever was ♫  ",
            "accion": "",
            "postFoto1": "",
            "altPostFoto1": "",
            "postFoto2": " ",
            "altPostFoto2": "",
            "postFoto3": "",
            "altPostFoto3": "",
            "postFoto4": "",
            "altPostFoto4": "",
            "score-lighthouse": "",
            "img-score-lighthouse": "",
        },
    ]
};

w3.displayObject("siteMap", myObject);

//   <time datetime="2021-04-29T20:10:18.429Z">29 April 2021</time>
// <a href = "https://github.com/alfio-event/alf.io" > Gestion de tickets < /a>>   
// Tatoe hi no naka mizu no naka  kusa no naka mori no naka

// Breaking Bad - Walter White Blue Meth